name: "Terraform PR Build"

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  versioning:
    permissions:
      contents: read
    uses: TerrAHCOF/workflow_core/.github/workflows/terraformPR.yml@main
    with:
      solutionDirectory: ./src/validation
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      client_id: ${{ secrets.AZURE_AD_CLIENT_ID }}
      client_secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      tenant_id: ${{ secrets.AZURE_AD_TENANT_ID }}
