name: "Versioning"

on:
  push:
    branches: ["main"]

jobs:
  versioning:
    permissions:
      contents: write
    uses: TerrAHCOF/workflow_core/.github/workflows/versioning.yml@main
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
